# Generated by Django 4.2.4 on 2023-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_comment_news_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
        migrations.AddField(
            model_name='news',
            name='Categories',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
