# Generated by Django 4.2.4 on 2023-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='C:\\Users\\86186\\2023Summer\\news_web\\main\\images\\default.jpg', upload_to='images/'),
        ),
    ]
