# Generated by Django 4.2.4 on 2023-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_image_image_file_image_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='images\\default.jpg', upload_to='images/'),
        ),
    ]
