# Generated by Django 4.2.4 on 2023-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_image_image_path_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
