# Generated by Django 4.2.4 on 2023-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_image_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('news_ids', models.TextField()),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
